# Worker 项目的名称
name = "phoenix"
# Worker 项目的入口文件，Wrangler 会打包部署它
main = "index.js"
# 兼容性日期是部署必须的
compatibility_date = "2025-11-03"
keep_vars = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

# 绑定 Cloudflare KV 存储
[[kv_namespaces]]
binding = "C"
# KV 命名空间 ID
id = "635123f949cb400d8adad7a43bb5f1b1"
